🔀 :: (#49) temporary api setting
Software-Meister-High-School-Community/MOIZA-Front-V1 pull request #75
Opened 2022-07-24 16:48 UTC by potatovllage

2022-07-26 06:27 UTC, paperdeer requested changes

2022-07-26 06:27 UTC, paperdeer commented on src/components/post/editpost/constant.ts
> +    summary: '게임',
이거 components > common > select > dropdown > option.ts에 있어요

2022-07-26 06:27 UTC, paperdeer commented on src/components/post/postwrite/constant.ts
> +  summary: string;
editpost의 constant와 겹치는건 뺴내주세요

2022-07-26 06:27 UTC, paperdeer commented on src/components/post/temporary/edittemp/constant.ts
> +  id: TCategory;
똑같은 코드가 많이 보이는데 이렇게 나눈 이유가 있나요

2022-07-26 06:27 UTC, paperdeer commented on src/components/post/temporary/edittemp/style.ts
> +  display: flex;
엄... 똑같은 내용인거 같은데 파일을 새로 판 이유가 있을까요

2022-07-29 10:05 UTC, ldh3907 approved these changes
좋습니다

2022-07-29 11:50 UTC, paperdeer approved these changes

2022-07-29 12:01 UTC, merged