🔀 :: (#71) feeds api settings
Software-Meister-High-School-Community/MOIZA-Front-V1 pull request #77
Opened 2022-08-12 05:01 UTC by potatovllage

2022-08-12 10:00 UTC, woojae05 reviewed
수고했어 👍

2022-08-12 10:00 UTC, woojae05 commented on src/components/post/postReply/PostReplyCommentOfComment/PostReplyCOCForm/index.tsx
> +            <strong>{author.author.name}</strong>
author안에 바로 name을 하는 게 좋아보여

2022-08-12 14:04 UTC, paperdeer requested changes

2022-08-12 14:04 UTC, paperdeer commented on src/components/common/button/heartButton/index.tsx
> +import { Like, DeleteLike } from '../../../../utils/api/feeds/index';
함수는 카멜케이스가..

2022-08-12 14:04 UTC, paperdeer commented on src/components/common/button/heartButton/index.tsx
>        console.log('like');
console은 지워주세요

2022-08-12 14:16 UTC, potatovllage commented on src/components/common/button/heartButton/index.tsx
> +import { Like, DeleteLike } from '../../../../utils/api/feeds/index';
전 있는거 가져왔을 뿐이에요;;

2022-08-12 14:16 UTC, potatovllage commented on src/components/common/button/heartButton/index.tsx
> +import { Like, DeleteLike } from '../../../../utils/api/feeds/index';
고치겠습니다

2022-08-12 15:26 UTC, ldh3907 approved these changes
좋습니다!

2022-08-13 10:01 UTC, woojae05 approved these changes

2022-08-15 02:22 UTC, paperdeer requested changes

2022-08-15 02:22 UTC, paperdeer commented on src/components/common/button/heartButton/index.tsx
> +    if (liked === false) {
!liked -> liked === false로 바꾼 이유가 있나요

2022-08-15 02:22 UTC, paperdeer commented on src/components/post/postReply/PostComment/index.tsx
> +          return <PostReplyCommentOfComment child_comments={child_comments} />;
이거 제대로 작동해요?

2022-08-15 02:22 UTC, paperdeer commented on src/components/post/postReply/PostComment/index.tsx
> +          return <PostReplyCommentOfComment child_comments={child_comments} />;
return 안에 또 return..?

2022-08-15 02:22 UTC, paperdeer commented on src/hooks/post/useComment.ts
> +    picture: [],
더미값 같은데 지워주세요

2022-08-15 02:22 UTC, paperdeer commented on src/hooks/post/useComment.ts
> +  };
이거도

2022-08-15 12:12 UTC, potatovllage commented on src/hooks/post/useComment.ts
> +    picture: [],
댓글 작업 할 때 지우려고 남겨놓았습니다

2022-08-15 14:19 UTC, paperdeer approved these changes

2022-08-15 14:20 UTC, merged